					ORG 0000H
					SJMP BASLA
					ORG 0003H
					SJMP KESMEINT0
					ORG 000BH
					SJMP KESMET0
					ORG 0013H
					SJMP KESMEINT1
					ORG 001BH
					SJMP KESMTET1
BASLA:				CLR P1.0
					MOV TMOD,#12H;T0 MOD 1 (50K SAYICAK) T1 MOD 2 (250 SAYICAK)
					MOV TH0, -250;T0 AYARLANIYOR
					MOV TL0, -250
					MOV TH1,HIGH(-50000);T1 AYARLANIYOR
					MOV TL1,LOW(-50000)
					MOV IE,#8FH;KESME ICIN IE REGISTERI AYARLANIYOR
					SETB IT0;DUSEN KENAR ICIN INT0
					SETB IT1;DUSEN KENAR ICIN INT1
					CLR P1.3;MOTOR BASLANGICDA DURMALI
					CLR TF0;TIMER DEGERLERI SIFIRLANDI
					CLR TF1
					CLR TR0
					CLR TR1
					SJMP $

KESMEINT1:			SETB P1.1;VANA1 AKTIF OLDU
					MOV TH1,HIGH(-50000);T1 TEKRAR KURULDU SUREKLI CALISMA ICIN
					MOV TL1,LOW(-50000)
					SETB TR1;T1 BASLATILDI
					RETI
					
KESMTET1:			CLR TR1;T1 SIFIRLANDI
					CLR TF1;TIMER FLAG SIFIRLANDI
					JB P1.0,MOTORCALISIYOR
					;MOTORCALISMIYORSA
					SETB P1.0
					SETB P1.2
					CLR TF0
					SETB TR0
					SJMP ATLA
					;MOTOR CALISIYORSA
MOTORCALISIYOR:		CLR P1.0
					CLR P1.2
					CLR TR0
					CLR TF0
ATLA:				RETI
					
KESMET0:			CLR TF0
					CPL P1.3
					RETI
KESMEINT0:			CLR P1.1
					MOV TH1,HIGH(-25000)
					MOV TL1,LOW(-25000)
					SETB TR1
					RETI
					END